apiVersion: batch/v1
kind: Job
metadata:
  name: index-creation-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-elastic
          image: busybox
          command: ["sh", "-c", "sleep 30"]
      containers:
        - name: index-creation
          image: us-central1-docker.pkg.dev/project-916342a2-cb14-4046-bc7/ollamacloud/index_creation_service:latest
