# ================================
# Embedding Service
# ================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding_service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embedding_service
  template:
    metadata:
      labels:
        app: embedding_service
    spec:
      containers:
        - name: embedding_service
          image: us-central1-docker.pkg.dev/project-916342a2-cb14-4046-bc7/ollamacloud/embedding_service:latest
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: embedding_service
spec:
  selector:
    app: embedding_service
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP

# ================================
# Elasticsearch (elasticdb)
# ================================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticdb
  template:
    metadata:
      labels:
        app: elasticdb
    spec:
      containers:
        - name: elasticdb
          image: us-central1-docker.pkg.dev/project-916342a2-cb14-4046-bc7/ollamacloud/elasticdb:latest
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: elasticdb
spec:
  selector:
    app: elasticdb
  ports:
    - port: 9200
      targetPort: 9200
  type: ClusterIP

# ================================
# Streamlit UI Service
# ================================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit_service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit_service
  template:
    metadata:
      labels:
        app: streamlit_service
    spec:
      initContainers:
        - name: wait-for-backend
          image: busybox
          command:
            - sh
            - -c
            - "sleep 60"
      containers:
        - name: streamlit
          image: us-central1-docker.pkg.dev/project-916342a2-cb14-4046-bc7/ollamacloud/streamlit_service:latest
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit_service
spec:
  selector:
    app: streamlit_service
  ports:
    - port: 8501
      targetPort: 8501
  type: LoadBalancer

# ================================
# Index Creation Service (One-time Job)
# ================================
---
apiVersion: batch/v1
kind: Job
metadata:
  name: index-creation-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-elasticsearch
          image: busybox
          command:
            - sh
            - -c
            - "sleep 30"
      containers:
        - name: index_creation_service
          image: us-central1-docker.pkg.dev/project-916342a2-cb14-4046-bc7/ollamacloud/index_creation_service:latest
