apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit_service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit_service
  template:
    metadata:
      labels:
        app: streamlit_service
    spec:
      initContainers:
        - name: wait-for-services
          image: busybox
          command:
            [
              "sh",
              "-c",
              "sleep 60"
            ]
      containers:
        - name: streamlit
          image: us-central1-docker.pkg.dev/project-916342a2-cb14-4046-bc7/ollamacloud/streamlit_service:latest
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit_service
spec:
  selector:
    app: streamlit_service
  ports:
    - port: 8501
      targetPort: 8501
  type: LoadBalancer
